services:
  prometheus:
    image: prom/prometheus:v2.50.1
    container_name: prometheus
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yaml",
        "--storage.tsdb.path=/prometheus",
        "--web.enable-lifecycle",
      ]
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:10.3.3
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  prometheus-storage:
